### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by altcnews** [thiago-scherrer/gotrader#1]
Hi,

I've got this error when running:

Starting a new round => GoTrader Bot
telegram error, API response are: 
quiting, API response are:  404
json: cannot unmarshal object into Go value of type []main.APIResponseComplex

Could you please help?
Thanks.

**Comment by thiago-scherrer** [comment]
Hello! 

Thanks for using the GoTrade. I will really enjoy receiving feedbacks and pullrequests :)

You need to configure the token and channel from **Telegram**, on config.yml like this:

```
telegram_key: "xxxx:xxxxxxxxxxxxxxxx"
telegramchannel: "@xxxxxxxx"
```

And you need to configure the **ENDPOINT** from **BITMEX**. But I strongly recommend you use testnet, so do not lose money:

```
endpoint: https://testnet.bitmex.com
```

Don't forget to move/copy the **configs/config-example.yml** to the **configs/config.yml** .

**Comment by altcnews** [comment]
Hi,
Thanks for replying.
Unfortunately, i still got the error

Successfully built 5fdf4224d176
Successfully tagged gotrader_gotrader:latest
Starting gotrader_gotrader_1 ... done
Starting a new round => GoTrader Bot
telegram error, API response are: 
Starting a new round => GoTrader Bot
telegram error, API response are: 

Already using my newest telegram bot id but still stop at that point. 
Any tips for disabling the telegram for testing purpose?

Appreciate for your kindly help.
Regards.

**Comment by thiago-scherrer** [comment]
Hi!

I just sent it to Master, the support to enable / disable the telegram.
Please, take a test and see if everything is ok!

Thank you very much for the feedback!

**Comment by altcnews** [comment]
Hi,
Thanks. I made my own changed the API key at bones.go in my personal folder, just in case it would be the case on my side.

There is no error from telegram anymore, i changed the candle to 1 and just to see if it works.
This is the result:

https://imgur.com/hfFcHB7

Is that working? I see no trigger at all using 1m candle, or do i have to change others parameters?
Best Regards.

**Comment by thiago-scherrer** [comment]
Nice!
Yes, It seems to be working!

Take a look at the parameters:

```
threshold: 3
profit: 0.60
```

I'll create a debug mode soon.
I'm closing this issue, in case you find another problem let me know!
Thank you!
